apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.tls: "false"
    ingress.kubernetes.io/rewrite-target: /
  namespace: airflow

spec:
  rules:
  - host: airflow.net #change it from here: C:\Windows\System32\drivers\etc
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: airflow-webserver
            port:
              number: 8080
