apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
  namespace: airflow
  # annotations:
  #   docker.io/hostpath: /var/lib/k8s-pvs/airflow-logs  ##docker path in local sys
  #   pv.kubernetes.io/provisioned-by: docker.io/hostpath
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /var/lib/k8s/airflow-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - "docker-desktop"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pvc
  namespace: airflow

spec:
  volumeName: airflow-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
