name: cleanup

on:
  workflow_dispatch:
    inputs:
      AreYouSure:
        description: "Cleanup unused Docker Images?"
        required: false
        default: "yes"
        type: string
  schedule:
    - cron: '0 0 * * *'
  workflow_run:
      workflows: ["Deploy Airflow","Deploy lakefs","Deploy Spark","Deploy kafka"]
      types:
        - completed
        
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Cleanup Unused Image
      run: |
        docker prune -a -f
