name: test-self-hosted

on:
  workflow_dispatch:
    inputs:
      AreYouSure:
        description: "AreYouSure?"
        required: false
        default: "Yup"
        type: string

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World"
