name: Deploy-Spark
on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Dockerfile to use for build."
        required: false
        default: "spark/Dockerfile"
        type: string
      tag:
        description: "Image tag to use"
        required: false
        type: string

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: upgrade helm
        run: |
          helm upgrade --install spark oci://registry-1.docker.io/bitnamicharts/spark --namespace spark --create-namespace  -f spark/spark_values.yaml  --debug
